### ISSUE TITLE
Question regarding a "stable" env

### ISSUE THREAD

**Issue by abbetch** [e-id-admin/public-sandbox-trustinfrastructure#16]
Hi,

I have a question regarding the needs for the stable environment that is described in the cookbook.

I'm on my way to generate the needed information (DID, ...) that seems to be completely doable in a local env. But it seems that I need to have a stable env to apply for the public sandbox trust infrastructure. 

What do you mean exactly by "Public reachable agent". Should my agent be completely accessible for the web ? with a static IP or a dedicated DNS ? Is there any "api" I could try, to interrogate my agent, and be sure it has a 'healthy' status regarding its reachability ? 

Or maybe is there already another agent, deployed by anyone else that I could use to generate my DID to finish applying to the sandbox trust infrastructure ?

**Comment by bruno-zimmermann-bit** [comment]
Hello

In the cookbook you are creating the Issuer. A wallet (potentially a mobile device) needs to be able to connect to the issuer to get a credential issued. See [3. Create an invitation]( https://github.com/e-id-admin/public-sandbox-trustinfrastructure/tree/main/cookbook#3-create-an-invitation) where you will create an invitation-link to be used by the wallet app.


The easiest way to achieve access from the wallet to the issuer, is to have your agent completely accessible from the web.
To test access, you can GET your public DID using the public URI. ` GET /wallet/did/public`

Your agent is protected by the API-Key set in the environment variables.

The IP address of the issuer-agent does not have to be static, because this information is updated after each start of the agent (with a special [attr transaction to the ledger]( https://explorer.sandbox.ssi.ch/txs/SANDBOX/domain?page=1&pageSize=50&filterTxNames=[%22ATTRIB%22]&sortFromRecent=true))
